In [ ]:
import numpy as np

CREATING ARRAY USING NUMPY

In [ ]:
ordinary_list = [1,2,3,4,5]
np.array(ordinary_list)

array([1, 2, 3, 4, 5])

In [ ]:
nested_list = [[1,2],[3,4],[5,6]]
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

ARANGE FUNCTION

In [ ]:
#keeps the array elements as integers only
print(np.arange(0,12))
print(np.arange(0,12,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 3 6 9]


ZEROS AND ONES FUNCTION

In [ ]:
#ZEROS : creates 0 as element but in float type but it can be changed like the way done in the next block. Same apply for ones.
print(np.zeros(3))

[0. 0. 0.]


In [ ]:
print(np.zeros((4,5), dtype= int))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
print(np.ones(5))

[1. 1. 1. 1. 1.]


LINSPACE FUNCTION

In [ ]:
#THE PARAMETERS ARE STARING AND ENDING POINT AND THE NUMBER OF ELEMENTS TO BE PRESENT IN THE ARRAY
print(np.linspace(0,10,4))

[ 0.          3.33333333  6.66666667 10.        ]


EYE FUNCTION

In [ ]:
#CREATES A SQUARE MATRIX WITH 1 AS THE DIAGONAL ELEMENTS.
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


RANDOM FUNCTION

In [ ]:
#RANDOM.RAND : CREATES AN ARRAY OF RANDOM ELEMENTS WITHIN THE RANGE (0,1)
print(np.random.rand(2))

[0.24182132 0.85368926]


In [ ]:
print(np.random.rand(4,5))

[[0.82088881 0.64003538 0.74686925 0.45424782 0.23721932]
 [0.91259879 0.21594095 0.28892803 0.36572921 0.81461306]
 [0.42357228 0.07533481 0.62038492 0.40554256 0.24915525]
 [0.740834   0.42699379 0.95075776 0.85767673 0.96821861]]


In [ ]:
#random.randn : creates the matrix with standard variance of 1
print(np.random.randn(3,4))

[[ 1.38464204  0.107744    1.23626811 -1.23536029]
 [ 0.49012306  0.55644801 -1.61721106 -0.02599342]
 [-0.0196301  -0.22564949  0.5192505   0.11811384]]


In [ ]:
np.random.randint(1, 100 , 10)

array([74, 92, 65, 11, 55, 91, 67, 17, 35, 22])

In [ ]:
np.random.randint(1, 100 , (3,4))

array([[94, 66, 41, 41],
       [ 3, 82, 65, 66],
       [59, 27, 85, 92]])

In [ ]:
np.random.seed(42)
print(np.random.rand(4))
#seed helps to create same random values like other user might be creating with the same seed value.

[0.37454012 0.95071431 0.73199394 0.59865848]


RESHAPE FUNCTION

In [ ]:
a = np.linspace(0,50,25)
print(a)

[ 0.          2.08333333  4.16666667  6.25        8.33333333 10.41666667
 12.5        14.58333333 16.66666667 18.75       20.83333333 22.91666667
 25.         27.08333333 29.16666667 31.25       33.33333333 35.41666667
 37.5        39.58333333 41.66666667 43.75       45.83333333 47.91666667
 50.        ]


In [ ]:
a.shape

(25,)

In [ ]:
a = a.reshape(5,5)

In [ ]:
a.max() #returns the maximum value in the array

50.0

In [ ]:
a.argmax() #return the index of the element with maximum value.

24

In [ ]:
print(a.min())
print(a.argmin())

0.0
0


In [ ]:
print(a.shape)
print(a.dtype)

(5, 5)
float64


INDEXING AND SELECTION:

GRABBING A SINGLE ELEMENT 

In [ ]:
A = np.arange(0,11)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(A[4])

4


GRABBING A SLICE OF ELEMENTS

In [ ]:
print(A[1:])

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
A[1:4]

array([1, 2, 3])

In [ ]:
A[1:4] = 100
print(A)
A = np.arange(0,11)

[  0 100 100 100   4   5   6   7   8   9  10]


In [ ]:
A[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
A_copy = A.copy()

BROADCASTING SELECTIONS

INDEXING AND SELECTION IN 2 DIMENSIONS

In [ ]:
x = np.array([[5,10,15] , [20,25,30] , [35,40,45]])
print(x)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [ ]:
x.shape

(3, 3)

In [ ]:
print(x[1,1])
print(x[1][1])

25
25


In [ ]:
x[0:2 , 1:]

array([[10, 15],
       [25, 30]])

CONDITIONAL SELECTIONS

In [ ]:
bool_x = x > 23
print(bool_x)
print(x[bool_x])

[[False False False]
 [False  True  True]
 [ True  True  True]]
[25 30 35 40 45]


NUMPY OPERATIONS:

In [ ]:
x+3

array([[ 8, 13, 18],
       [23, 28, 33],
       [38, 43, 48]])

In [ ]:
np.sqrt(x)

array([[2.23606798, 3.16227766, 3.87298335],
       [4.47213595, 5.        , 5.47722558],
       [5.91607978, 6.32455532, 6.70820393]])

In [ ]:
np.sin(x)

array([[-0.95892427, -0.54402111,  0.65028784],
       [ 0.91294525, -0.13235175, -0.98803162],
       [-0.42818267,  0.74511316,  0.85090352]])

In [ ]:
np.log(x)

array([[1.60943791, 2.30258509, 2.7080502 ],
       [2.99573227, 3.21887582, 3.40119738],
       [3.55534806, 3.68887945, 3.80666249]])